steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--tag', 'gcr.io/$PROJECT_ID/my-app:latest', '.']
options:
  logsBucket: 'gs://your-logs-bucket-name'
  logging: 'GCS_ONLY'
