steps:
- name: 'maven:3.9.6-eclipse-temurin-17'
  entrypoint: mvn
  args: ['clean', 'install', '-Dmaven.test.skip=true']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-east1-docker.pkg.dev/for-tech-practice/sample-test/sampletest-image', '.']
  # Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-east1-docker.pkg.dev/for-tech-practice/sample-test/sampletest-image']
  # Deploy image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'sample-test', '--image', 'asia-east1-docker.pkg.dev/for-tech-practice/sample-test/sampletest-image', '--region', 'asia-east1']
images: ['asia-east1-docker.pkg.dev/for-tech-practice/sample-test/sampletest-image']
logsBucket: 'gs://cloud-build-log123'
serviceAccount: 'projects/for-tech-practice/serviceAccounts/for-cloud-build-deploy@for-tech-practice.iam.gserviceaccount.com'
options:
  logging: GCS_ONLY
