steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'asia-east1-docker.pkg.dev/for-tech-practice/sample-test/sampletest-image', '.']
images: ['asia-east1-docker.pkg.dev/for-tech-practice/sample-test/sampletest-image']
