    steps:
    - name: 'ubuntu' # Or any builder image that provides shell access
      args: ['chmod', '+x', './mvnw']
    - name: 'gcr.io/cloud-builders/mvn' # Or a custom Maven builder image
      args: ['./mvnw', 'clean', 'install'] # Execute mvnw